- name: talk-proposal
  color: "0E8A16"
  description: New talk proposal for Kubeflow Commons Hub meetup

- name: scheduled
  color: "5319E7"
  description: The scheduled talks

- name: newsletter
  color: "1D76DB"
  description: Collection box for links of this month

- name: submitted
  color: "FBCA04"
  description: Talk proposal submitted

- name: enhancement
  color: "A2EEEF"
  description: New feature or request

